spring:
  application:
    name: ${APP_NAME:pr-lab1-consumer-dev}

server:
  address: ${ADDRESS:localhost}
  port: ${PORT:8088}
  id: ${RESTAURANT_ID:0}

producer:
  address: ${PRODUCER_ADDRESS:localhost}
  port: ${PRODUCER_PORT:8077}

kitchen:
  time:
    unit: ${KITCHEN_TIME_UNIT:1}
    duration: ${KITCHEN_TIME_DURATION:100}
  cooks:
    count: ${COOKS_COUNT:4}
  apparatus:
    oven: ${OVENS_COUNT:2}
    stove: ${STOVE_COUNT:1}

cooksList:
  -
    rank: 3
    proficiency: 4
    name: "Cook 1"
  -
    rank: 2
    proficiency: 3
    name: "Cook 2"
  -
    rank: 2
    proficiency: 2
    name: "Cook 3"
  -
    rank: 1
    proficiency: 2
    name: "Cook 4"

food-ordering:
  address: ${ORDERING_ADDRESS:localhost}
  port: ${ORDERING_PORT:8002}