spring:
  application:
    name: ${APP_NAME:pr-lab1-consumer-dev}

server:
  address: ${ADDRESS:0.0.0.0}
  port: ${PORT:8088}

producer:
  address: ${PRODUCER_ADDRESS:http://localhost}
  port: ${PRODUCER_PORT:8070}

kitchen:
  time:
    unit: ${KITCHEN_TIME_UNIT:1}
    duration: ${KITCHEN_TIME_DURATION:100}
  cooks:
    count: ${COOKS_COUNT:2}
  apparatus:
    oven: ${OVENS_COUNT:2}
    stove: ${STOVE_COUNT:1}

  cooks_list:
    - rank: 3
      proeﬁciency: 4
      name: "Cook 1"
    - rank: 2
      proeﬁciency: 3
      name: "Cook 2"
    - rank: 2
      proeﬁciency: 2
      name: "Cook 3"
    - rank: 1
      proeﬁciency: 2
      name: "Cook 4"